spring:
  application:
    name: demo
  datasource:
    url: postgresql://localhost:5432/projectDB
    username: postgres
    password: db1234
  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
timer:
  maxrecords: 10
api:
  url: ${http://api.quotable.io/random}
server:
  port: 9000